[tools]
node = "23.5.0"
"npm:@biomejs/biome" = "1.9.4"
bun = "1.1.42"

[env]
_.path = "node_modules/.bin"

[tasks]
fmt = "biome check --fix --unsafe ."
gen-spec = "bun run scripts/gen-spec.ts"
typecheck = "tsc --noEmit"
test = "vitest {% if get_env(name='CI', default='') == 'true' %} --run {% endif %}"
